import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { BookContent, BookAnalysis, CopyrightInfo, GeneratorOutput } from '../types.js';
import { log } from '../logger.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = join(__dirname, '..', '..', 'templates', 'mcp-server');

/**
 * Generate a standalone MCP server project from book analysis.
 * The server embeds book data as TypeScript constants and provides
 * tools for searching content, getting chapters, and retrieving principles.
 */
export async function generateMcpServer(
  book: BookContent,
  analysis: BookAnalysis,
  copyright: CopyrightInfo,
  outputDir: string
): Promise<GeneratorOutput> {
  log.header('Generating MCP server project...');

  mkdirSync(join(outputDir, 'src'), { recursive: true });

  const files: string[] = [];
  const slug = slugify(book.metadata.title);
  const packageName = `mcp-${slug}`;

  // 1. package.json
  const pkgTemplate = readFileSync(join(TEMPLATES_DIR, 'package.template.json'), 'utf-8');
  const pkg = pkgTemplate
    .replace(/\{\{PACKAGE_NAME\}\}/g, packageName)
    .replace(/\{\{BIN_NAME\}\}/g, packageName)
    .replace(/\{\{DESCRIPTION\}\}/g, `MCP server for "${book.metadata.title}" by ${book.metadata.author}`);
  writeFileSync(join(outputDir, 'package.json'), pkg, 'utf-8');
  files.push('package.json');

  // 2. tsconfig.json
  const tsconfigTemplate = readFileSync(join(TEMPLATES_DIR, 'tsconfig.template.json'), 'utf-8');
  writeFileSync(join(outputDir, 'tsconfig.json'), tsconfigTemplate, 'utf-8');
  files.push('tsconfig.json');

  // 3. src/data.ts — embedded book data
  const dataTs = generateDataModule(book, analysis, copyright);
  writeFileSync(join(outputDir, 'src', 'data.ts'), dataTs, 'utf-8');
  files.push('src/data.ts');
  log.info('Generated src/data.ts (embedded book data)');

  // 4. src/index.ts — MCP server implementation
  const indexTs = generateServerModule(book, analysis);
  writeFileSync(join(outputDir, 'src', 'index.ts'), indexTs, 'utf-8');
  files.push('src/index.ts');
  log.info('Generated src/index.ts (MCP server)');

  // 5. README.md
  const readme = generateReadme(book, analysis, copyright, packageName);
  writeFileSync(join(outputDir, 'README.md'), readme, 'utf-8');
  files.push('README.md');

  // 6. .gitignore
  writeFileSync(join(outputDir, '.gitignore'), 'node_modules/\ndist/\n', 'utf-8');
  files.push('.gitignore');

  log.success(`MCP server generated at ${outputDir}`);

  return { format: 'mcp', outputDir, files };
}

function generateDataModule(
  book: BookContent,
  analysis: BookAnalysis,
  copyright: CopyrightInfo
): string {
  // Embed book content as TypeScript constants
  const chapters = book.chapters.map((ch) => ({
    title: ch.title,
    order: ch.order,
    wordCount: ch.wordCount,
    content: ch.sections.map((s) => s.content).join('\n\n'),
  }));

  const principles = analysis.principles.map((p) => ({
    name: p.name,
    description: p.description,
    sourceChapter: p.sourceChapter,
    actionable: p.actionable,
  }));

  const frameworks = analysis.frameworks.map((f) => ({
    name: f.name,
    description: f.description,
    type: f.type,
    steps: f.steps,
    sourceChapter: f.sourceChapter,
  }));

  return `// Auto-generated by book-power — do not edit manually

export const BOOK_INFO = ${JSON.stringify({
    title: book.metadata.title,
    author: book.metadata.author,
    url: book.metadata.url,
    license: copyright.licenseFullName,
    totalChapters: book.totalChapters,
    totalWordCount: book.totalWordCount,
    summary: analysis.summary,
    expertise: analysis.expertise,
    tone: analysis.tone,
    audienceLevel: analysis.audienceLevel,
  }, null, 2)} as const;

export const CHAPTERS = ${JSON.stringify(chapters, null, 2)} as const;

export const PRINCIPLES = ${JSON.stringify(principles, null, 2)} as const;

export const FRAMEWORKS = ${JSON.stringify(frameworks, null, 2)} as const;
`;
}

function generateServerModule(book: BookContent, analysis: BookAnalysis): string {
  const serverName = slugify(book.metadata.title);

  return `#!/usr/bin/env node
// Auto-generated MCP server by book-power

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import { BOOK_INFO, CHAPTERS, PRINCIPLES, FRAMEWORKS } from './data.js';

const server = new Server(
  { name: '${serverName}', version: '0.1.0' },
  { capabilities: { tools: {} } }
);

// --- Tool definitions ---

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: 'get_book_info',
      description: 'Get overview information about the book: title, author, summary, expertise areas',
      inputSchema: { type: 'object', properties: {} },
    },
    {
      name: 'search_content',
      description: 'Search the book content for a keyword or phrase. Returns matching passages with chapter context.',
      inputSchema: {
        type: 'object',
        properties: {
          query: { type: 'string', description: 'Search query' },
          max_results: { type: 'number', description: 'Maximum results to return (default: 5)' },
        },
        required: ['query'],
      },
    },
    {
      name: 'get_chapter',
      description: 'Get the full content of a specific chapter by name or number',
      inputSchema: {
        type: 'object',
        properties: {
          chapter: { type: 'string', description: 'Chapter name or number (1-based)' },
        },
        required: ['chapter'],
      },
    },
    {
      name: 'get_principles',
      description: 'Get all key principles extracted from the book',
      inputSchema: {
        type: 'object',
        properties: {
          actionable_only: { type: 'boolean', description: 'Only return actionable principles' },
        },
      },
    },
    {
      name: 'get_frameworks',
      description: 'Get all frameworks and checklists extracted from the book',
      inputSchema: {
        type: 'object',
        properties: {
          type: { type: 'string', description: 'Filter by type: checklist, process, matrix, spectrum' },
        },
      },
    },
  ],
}));

// --- Tool implementations ---

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  switch (name) {
    case 'get_book_info':
      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify(BOOK_INFO, null, 2),
          },
        ],
      };

    case 'search_content': {
      const query = (args?.query as string || '').toLowerCase();
      const maxResults = (args?.max_results as number) || 5;
      const results: Array<{ chapter: string; excerpt: string; relevance: number }> = [];

      for (const chapter of CHAPTERS) {
        const content = chapter.content.toLowerCase();
        const idx = content.indexOf(query);
        if (idx !== -1) {
          // Extract surrounding context (200 chars each side)
          const start = Math.max(0, idx - 200);
          const end = Math.min(content.length, idx + query.length + 200);
          const excerpt = chapter.content.slice(start, end);

          // Simple relevance: count occurrences
          let count = 0;
          let pos = 0;
          while ((pos = content.indexOf(query, pos)) !== -1) {
            count++;
            pos += query.length;
          }

          results.push({
            chapter: chapter.title,
            excerpt: (start > 0 ? '...' : '') + excerpt + (end < content.length ? '...' : ''),
            relevance: count,
          });
        }
      }

      results.sort((a, b) => b.relevance - a.relevance);

      return {
        content: [
          {
            type: 'text',
            text: results.length > 0
              ? JSON.stringify(results.slice(0, maxResults), null, 2)
              : \`No results found for "\${args?.query}"\`,
          },
        ],
      };
    }

    case 'get_chapter': {
      const chapterArg = args?.chapter as string || '';
      const chapterNum = parseInt(chapterArg);

      const chapter = !isNaN(chapterNum)
        ? CHAPTERS[chapterNum - 1]
        : CHAPTERS.find(
            (c) => c.title.toLowerCase().includes(chapterArg.toLowerCase())
          );

      if (!chapter) {
        const available = CHAPTERS.map((c, i) => \`\${i + 1}. \${c.title}\`).join('\\n');
        return {
          content: [{ type: 'text', text: \`Chapter not found. Available chapters:\\n\${available}\` }],
        };
      }

      return {
        content: [
          {
            type: 'text',
            text: \`# \${chapter.title}\\n\\n\${chapter.content}\`,
          },
        ],
      };
    }

    case 'get_principles': {
      const actionableOnly = args?.actionable_only as boolean;
      const filtered = actionableOnly
        ? PRINCIPLES.filter((p) => p.actionable)
        : PRINCIPLES;

      return {
        content: [{ type: 'text', text: JSON.stringify(filtered, null, 2) }],
      };
    }

    case 'get_frameworks': {
      const typeFilter = args?.type as string;
      const filtered = typeFilter
        ? FRAMEWORKS.filter((f) => f.type === typeFilter)
        : FRAMEWORKS;

      return {
        content: [{ type: 'text', text: JSON.stringify(filtered, null, 2) }],
      };
    }

    default:
      return {
        content: [{ type: 'text', text: \`Unknown tool: \${name}\` }],
        isError: true,
      };
  }
});

// --- Start server ---

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch(console.error);
`;
}

function generateReadme(
  book: BookContent,
  analysis: BookAnalysis,
  copyright: CopyrightInfo,
  packageName: string
): string {
  return `# ${packageName}

MCP server providing tool-based access to "${book.metadata.title}" by ${book.metadata.author}.

## Tools

| Tool | Description |
|------|-------------|
| \`get_book_info\` | Book overview: title, author, summary, expertise areas |
| \`search_content\` | Search book content for keywords/phrases |
| \`get_chapter\` | Get full chapter content by name or number |
| \`get_principles\` | Key principles extracted from the book |
| \`get_frameworks\` | Frameworks and checklists from the book |

## Setup

\`\`\`bash
npm install
npm run build
\`\`\`

## Usage with Claude Code

Add to your \`~/.claude.json\`:

\`\`\`json
{
  "mcpServers": {
    "${packageName}": {
      "command": "node",
      "args": ["${packageName}/dist/index.js"]
    }
  }
}
\`\`\`

## Source

Generated by [book-power](https://github.com/zhiganov/book-power) from "${book.metadata.title}" by ${book.metadata.author} (${copyright.licenseFullName}).

## License

MIT
`;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
}
